### ISSUE TITLE
npm run start crash

### ISSUE THREAD

**Issue by shellwhale** [aronwoost/google-calendar-hours#190]
Hello, first of all, many thanks for this nice project.

I tried running it locally with `npm start` but I'm getting an error right off the bat. (I did the `npm install ` first)

```
~\repositories\google-calendar-hours ❯ npm start

> start
> node scripts/start.js

i ｢wds｣: Project is running at http://10.2.0.2/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\shellwhale\repositories\google-calendar-hours\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\shellwhale\repositories\google-calendar-hours\scripts\start.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\shellwhale\repositories\google-calendar-hours\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.8.1
```

**Comment by aronwoost** [comment]
I can confirm for node 18 and node 19. I will have a look (when I have time).

Until then you can try node 16. 👍
